# https://docs.docker.com/docker-cloud/apps/stack-yaml-reference
version: '3.1'
services:
  govcms:
    image: markfuller/govcms8
    ports:
      - 80:80
  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password