# https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#devices
version: '3.1'
services:
  govcms:
    image: markfuller/govcms8
    links:
      - db
    ports:
      - 80:80
  db:
    image: mariadb:10.2
    links:
      - govcms