# https://docs.docker.com/docker-cloud/apps/stack-yaml-reference
version: '3.1'
services:
  govcms:
    image: markfuller/govcms8
    ports:
      - 80:80
    networks:
      - webnet
  db:
    image: markfuller/database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
    networks:
      - webnet
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
networks:
  webnet:
