module:
  action: 0
  backup_migrate: 0
  ban: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_styles: 0
  breakpoint: 0
  ckeditor: 0
  clamav: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  formtips: 0
  gnode: 0
  group: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  libraries: 0
  link: 0
  mailsystem: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  path: 0
  rdf: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  statistics: 0
  styles_api: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  tracker: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  pathauto: 1
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  at_core: 0
  bartik: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
