formtips_trigger_action: hover
formtips_hoverintent: 1
formtips_timeout: 1000
formtips_interval: 500
formtips_sensitivity: 3
formtips_max_width: 500px
formtips_selectors: ''
_core:
  default_config_hash: CSEbykYXKQ8vZ2M2uuargqxJ_0nSKU8L1NUO4znRwxc
